# Secret patterns (refined for specificity)

SECRET_PATTERNS
{
    "Amazon AWS Access Key ID": r"(?i)AKIA[0-9A-Z]{16}",
    "Amazon MWS Auth Token": r"(?i)amzn\.mws\.[0-9a-f-]{36}",
    "Amazon AWS S3 URL": r"(?i)s3\.amazonaws\.com[/]+|[a-zA-Z0-9_-]*\.s3\.amazonaws\.com",
    "Facebook Access Token": r"(?i)EAACEdEose0cBA[0-9A-Za-z]+",
    "Authorization Basic": r"(?i)basic\s*[a-zA-Z0-9=:_\+/\-]+",
    "Authorization Bearer": r"(?i)bearer\s*[a-zA-Z0-9_\-\.=:_\+/]+",
    "Mailgun API Key": r"(?i)key-[0-9a-zA-Z]{32}",
    "Twilio API Key": r"(?i)SK[0-9a-fA-F]{32}",
    "Twilio Account SID": r"(?i)AC[a-zA-Z0-9_\-]{32}",
    "Stripe Standard API Key": r"(?i)sk_live_[0-9a-zA-Z]{24}",
    "Stripe Restricted API Key": r"(?i)rk_live_[0-9a-zA-Z]{24}",
    "GitHub Access Token": r"(?i)[a-zA-Z0-9_-]*:[a-zA-Z0-9_\-]+@github\.com*",
    "RSA Private Key": r"(?i)-----BEGIN RSA PRIVATE KEY-----",
    "JWT Token": r"(?i)ey[A-Za-z0-9\-_=]+\.[A-Za-z0-9\-_=]+\.?[A-Za-z0-9\-_.+/=]*$",
    "Slack Token": r"(?i)xox[baprs]-[0-9]{12}-[0-9]{12}-[0-9a-zA-Z]{24,32}",
    "Slack Webhook": r"(?i)https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}",
    "MongoDB URI": r"(?i)mongodb\+srv://[\w\-:.@]+",
    "Base64 Strings": r"(?i)\b[A-Za-z0-9+/]{40,}={0,2}\b",
    "Email Address": r"(?i)[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+",
    "Phone Number": r"(?i)(?:\+\d{1,3}[ \-]?)?(?:\(\d{1,4}\)[ \-]?)?\d{6,15}",
    "Username": r"(?i)(username|user_name|usr)\s*[:=]\s*[\"']?[a-zA-Z0-9_.-]{3,}[\"']?",
    "Password": r"(?i)(password|pass|pwd)\s*[:=]\s*[\"']?[a-zA-Z0-9!@#$%^&*()_+=-]{8,}['\"]?",
    "Generic Secrets": r"(?i)[\"']?(?:api|secret|access|auth|token|key)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9\-_]{20,}[\"']?",
    "GraphQL Schema": r"(?i)__schema|__type|GraphQL",
    "Internal API": r"(?i)https?://(?:dev|internal|staging|test|localhost|127\.0\.0\.1)[^\s\"']*",
    "Deprecated Endpoint": r"(?i)https?://[^\s\"']+/(v[0-9]+|legacy|old|deprecated)/[^\s\"']*",
    "Database URL": r"(?i)databaseURL\s*[:=]\s*[\"']?https?://[^\s\"']+[\"']?",
    "PayPal Braintree Access Token": r"(?i)access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}",
    "Square OAuth Secret": r"(?i)sq0csp-[ 0-9A-Za-z\-_]{43}|sq0[a-z]{3}-[0-9A-Za-z\-_]{22,43}",
    "Square Access Token": r"(?i)sqOatp-[0-9A-Za-z\-_]{22}|EAAA[a-zA-Z0-9]{60}",
    "GitHub Fine-Grained PAT": r"(?i)github_pat_[a-zA-Z0-9_]{82}",
    "SSH DSA Private Key": r"(?i)-----BEGIN DSA PRIVATE KEY-----",
    "SSH EC Private Key": r"(?i)-----BEGIN EC PRIVATE KEY-----",
    "PGP Private Key Block": r"(?i)-----BEGIN PGP PRIVATE KEY BLOCK-----",
    "Redis URI": r"(?i)redis://[a-zA-Z0-9_:-]+@[^\s]+",
    "Hugging Face Token": r"(?i)hf_[A-Za-z0-9]{32,}",
    "BrowserStack Credentials": r"(?i)(BROWSERSTACK_USERNAME|BROWSERSTACK_ACCESS_KEY)\s*=\s*[\"']?[\w-]+[\"']?",
    "Weights & Biases API Key": r"(?i)wandb_[a-z0-9]{32,}",
    "NGC Token": r"(?i)\$o2\s+[A-Za-z0-9\-._~+/]+=*",
    "Klaviyo API Key": r"(?i)pk_[a-z0-9]{32}",
    "DockerHub Credentials": r"(?i)(DOCKERHUB_USERNAME|DOCKERHUB_PASSWORD)\s*=\s*[\"']?[A-Za-z0-9_-]+[\"']?",
    "SonarCloud Token": r"(?i)sonar[_-]?token\s*[:=]\s*[\"']?[a-z0-9\-_]{20,}[\"']?",
    "AWS Secret Key": r"(?i)aws[_-]?secret[_-]?access[_-]?key\s*[:=]\s*[\"']?([A-Za-z0-9/+=]{40})[\"']?",
    "Slack Token Assignment": r"(?i)slackToken\s*=\s*['\"][a-zA-Z0-9-]+['\"]",
    "Filepicker Key": r"(?i)filepicker_[a-z]*key\s*=\s*['\"][a-zA-Z0-9]+['\"]",
    "Amazon MWS Key": r"(?i)amzn\.mws\.[a-zA-Z0-9-]+",
    "SK Key Pattern": r"(?i)\bsk_[a-zA-Z0-9_\-]{24,}\b",
    "SK Assignment": r"(?i)\bsk\s*=\s*['\"][a-zA-Z0-9_\-]{24,}['\"]",
    "SK in URL": r"(?i)[\?&]sk=[a-zA-Z0-9_\-]{24,}",
    "JWT in Variable": r"(?i)\b(?:jwt|token)\s*=\s*['\"]ey[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]*['\"]",
    "Hardcoded API Key": r"(?i)\b(?:api|secret|private|public)[_-]?key\s*[:=]\s*['\"][a-zA-Z0-9_\-]{20,}['\"]",
    "Config Object Secrets": r"(?i)\bconfig\s*=\s*{[^}]*?(?:api|secret|token|key)\s*:\s*['\"][a-zA-Z0-9_\-]{20,}['\"][^}]*}",
    "Firebase URL": r"(?i)[a-zA-Z0-9.-]+\.firebaseio\.com",
    "Heroku API Key": r"(?i)[hH]eroku[a-zA-Z0-9_-]*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}",
    "Admin Reference": r"(?i)\badmin\b",
    "1Password Service Account Token": r"(?i)ops_[a-zA-Z0-9]{59}",
    "Adobe Client Secret": r"(?i)adobe(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|\"]){0,3}(?:=|>|:)(?:'|\"|\s|=|\x60){0,5}([0-9a-f]{64})(?:['|\"|\n|\r|\s|\x60]|$)",
    "Airtable API Key": r"(?i)key[a-zA-Z0-9]{14}",
    "Airtable Personal Access Token": r"(?i)pat[a-zA-Z0-9]{14}\.[a-z0-9]{61}",
    "Alibaba Cloud Access Key ID": r"(?i)LTAI[0-9a-zA-Z]{16}",
    "Alibaba Cloud Access Key Secret": r"(?i)[0-9a-zA-Z]{30}",
    "Asana Personal Access Token": r"(?i)[0-9]\/[a-z0-9]{15}",
    "Azure DevOps Personal Access Token": r"(?i)[a-z0-9]{52}",
    "Anthropic API Key": r"(?i)sk-ant-[a-zA-Z0-9]{50}",
    "Apify API Token": r"(?i)apify_api_[a-zA-Z0-9]{32}",
    "Aiven Authentication Token": r"(?i)avn_[a-zA-Z0-9]{32}",
    "Azure AI Services Key": r"(?i)[a-z0-9]{32}",
    "Azure Batch Key": r"(?i)[a-zA-Z0-9\+/]{44}==",
    "Azure Cosmos DB Key": r"(?i)[a-zA-Z0-9\+/]{43}=",
    "OpenSSH Private Key": r"(?i)-----BEGIN OPENSSH PRIVATE KEY-----",
    "MySQL Connection String": r"(?i)mysql://[a-zA-Z0-9_:-]+:[a-zA-Z0-9_:-]+@[^\s]+",
    "PostgreSQL Connection String": r"(?i)postgres://[a-zA-Z0-9_:-]+:[a-zA-Z0-9_:-]+@[^\s]+",
}
